#pragma once
#define LITW
#define LITWVERSION "0.10.0"
#include <Window.hpp>
#include <userinput.hpp>
#include <Widget.hpp>
#include <windows/StartMenu.hpp>
#include <widgets/Button.hpp>
#include <widgets/text/Label.hpp>
#include <widgets/text/TextInput.hpp>
#include <widgets/text/LargeTextbox.hpp>
#include <widgets/text/ScrollableTextBox.hpp>
#include <widgets/text/LargeTextInput.hpp>
#include <widgets/containers/ScrollContainer.hpp>
#include <widgets/containers/VerticalContainer.hpp>
#include <widgets/containers/HorizontalContainer.hpp>
#include <widgets/Checkbox.hpp>
#include <widgets/Separator.hpp>
#include <widgets/Table.hpp>
#include <widgets/ShellWidget.hpp>
#include <widgets/EyesWidget.hpp>
#include <widgets/Toggle.hpp>